### ISSUE TITLE
2.1.0版本中青，最新的，好像有点问题

### ISSUE THREAD

**Issue by UniQiu** [ztxtop/x#1]
过去不了阅读body和看看赚的body，麻烦大佬更新一下，谢谢🙏

**Comment by ztxtop** [comment]
> 过去不了阅读body和看看赚的body，麻烦大佬更新一下，谢谢🙏

我账号不行了，阅读body问题关注下[Sunert大佬仓库](https://github.com/Sunert/Script/tree/master)的更新吧，看看赚跟浏览赚应该只需要更新下重写域名即可，我更新了库里的插件配置rewrite-zqkkz.plugin，你试试看

**Comment by UniQiu** [comment]
看看赚已经可以了，谢谢，辛苦了
