### ISSUE TITLE
老板，宠汪汪兑换需要修复一下

### ISSUE THREAD

**Issue by wexps7** [ztxtop/x#3]
有空，抽时间搞搞🙏

**Comment by ztxtop** [comment]
> 有空，抽时间搞搞🙏

通过验证需要nodejs环境，ios端软件目前没戏；网上已有大佬放出跳过验证并兑换的脚本及方法，你可能去找找看，或者去看看[姐姐的项目](https://github.com/CenBoMin/JDTASK_V2P)
