### ISSUE TITLE
中青

### ISSUE THREAD

**Issue by wcn666** [ztxtop/x#4]
请问中青多账号这个能不能出个教程呀，用了好久用qx都添加不了

**Comment by ztxtop** [comment]
> 请问中青多账号这个能不能出个教程呀，用了好久用qx都添加不了

订阅下boxjs，看看中青数据的应用描述吧，不会出教程且脚本只是微改sunert大佬的，中青近半年更新了不少版本，不清楚获取多账号ck的脚本是否还正常，请自测，不行就老实按sunert大佬库里的说明描述去尝试操作吧

**Comment by wcn666** [comment]
好的好的，
